using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Support.UI;

namespace AdressBook_web_test
{
    
        public class ContactHelper : HelperBase
        {
           
            public ContactHelper(ApplicationManager manager) : base(manager)
        {
              
            }

        private List<ContactData> ContactCache = null;

        public List<ContactData> GetContactList()
        {

            if (ContactCache == null)
            {
              
                ContactCache = new List<ContactData>();
                List<String> Name = new List<String>();
                List<String> LastName = new List<String>();
                List<String> Id= new List<String>();


                ICollection<IWebElement> elementName = driver.FindElements(By.XPath("//td[3]"));

                ICollection<IWebElement> elementLastName = driver.FindElements(By.XPath("//td[2]"));

                ICollection<IWebElement> elementId= driver.FindElements(By.Name("selected[]"));
                //By.TagName("input[name = \"selected[]\"]\"")



                foreach (IWebElement element in elementId)
                {

                    
                    Id.Add(element.GetAttribute("value"));
                }


                foreach (IWebElement element in elementName)
                {

                    Name.Add(element.Text);
                    
                }

                foreach (IWebElement element in elementLastName)
                {

                    LastName.Add(element.Text);
                }

                for (int i = 0; i < elementName.Count; i++)
                {
                    ContactCache.Add(new ContactData(Name[i], LastName[i]) {Id = Id[i] });
                    
                }

                
            }

            return new List<ContactData>(ContactCache);
        }



        public ContactHelper Create(ContactData contact)
        {
            InitContactCreation();
            FillContactForm(contact);
            SubmitContactCreation();
            SubmitHome();
            return this;
        }

        public void AutoGenerationContact(int untillNumber)//новый  помощник
        {
            int CountAddContact = 0;
            while (!IsSelectContact(untillNumber))
            {
               // if (untillNumber == 0) break;
                InitContactCreation();
                FillContactForm(new ContactData($"CountAutoGenerated{CountAddContact}", "AddAutoContact"));
                SubmitContactCreation();
                SubmitHome();
                CountAddContact++;
            }
        }

        public ContactHelper Modify(int n, ContactData newcontact)
        {
           
                InitContactModify(n);
                FillContactForm(newcontact);
                SubmitContactModify();
                SubmitHome();
            
            
                //SelectContact(n);  как показывает практика выделение контакта перед изменением ничего не дает.Нужен конкретный клик по иконке
               
            return this;
           
        }

        public ContactHelper SelectContact(int n)
        {
            driver.FindElement(By.XPath($"//table[@id='maintable']/tbody/tr[{2+n}]/td")).Click();
            return this;
        }
        public bool IsSelectContact(int n)
        {
            return IsElementPresent(By.XPath($"//table[@id='maintable']/tbody/tr[{2 + n}]/td"));
        }

        public ContactHelper Remove(int v)
        {
            
                SelectContact(v);
                SubmitContactRemove();
            ContactCache = null;



            return this;
        }

        public ContactHelper SubmitContactRemove()
        {
            driver.FindElement(By.XPath("//input[@value='Delete']")).Click();
           // driver.SwitchTo().Alert().Accept();// закрыть Алерт? какой алерт?
            return this;
        }

        public ContactHelper SubmitContactModify()
        {
            driver.FindElement(By.XPath("//input[21]")).Click();
            ContactCache = null;
            return this;
        }

        public ContactHelper InitContactModify(int n)
        {
            // driver.FindElement(By.CssSelector("img[alt=\"Edit\"]")).Click(); первая иконка
            driver.FindElement(By.XPath($"//table[@id='maintable']/tbody/tr[{2+n}]/td[8]/a/img")).Click();  //все вроме первой, но возможно и первую найдет
            return this;
        }

        public ContactHelper InitContactCreation()
        {
            driver.FindElement(By.LinkText("add new")).Click();
            return this;
        }

        public ContactHelper FillContactForm(ContactData contact)
        {
            Type(By.Name("firstname"), contact.Name);
            Type(By.Name("lastname"), contact.LastName);
           
            return this;
        }

        public ContactHelper SubmitContactCreation()
        {
            driver.FindElement(By.XPath("//div[@id='content']/form/input[20]")).Click();
            ContactCache = null;
            return this;
        }

        public ContactHelper SubmitHome()
        {
            driver.FindElement(By.LinkText("home")).Click();
            return this;

        }
        public int Count()
        {
            return driver.FindElements(By.XPath("//td[3]")).Count;
        }


    }

}
